
export const USER_VALIDATIONS = {
    NAME_MAX_LENGTH: 20,
    NAME_MIN_LENGTH: 2, 
    NAME_ERROR_MSG: "Name must be between 2 and 20 symbols.",

    FIRST_NAME_MAX_LENGTH: 20,
    FIRST_NAME_MIN_LENGTH: 2, 
    FIRST_NAME_ERROR_MSG: "First name must be between 2 and 20 symbols.",

    LAST_NAME_MAX_LENGTH: 20,
    LAST_NAME_MIN_LENGTH: 2, 
    LAST_NAME_ERROR_MSG: "Last name must be between 2 and 20 symbols.",

    COUNTRY_MAX_LENGTH: 20,
    COUNTRY_MIN_LENGTH: 2, 
    COUNTRY_ERROR_MSG: "Country must be between 2 and 20 symbols.",

    CITY_MAX_LENGTH: 20,
    CITY_MIN_LENGTH: 2, 
    CITY_ERROR_MSG: "City must be between 2 and 20 symbols.",

    PASSWORD_REGEX: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{6,}$/,
    PASSWORD_ERROR_MSG: "Password must be at least 6 symbols and should contain capital letter, digit and a special symbol.",
    REPEAT_PASSWORD_ERROR_MSG: "Confirm password does not match password.",
    EMPTY_PASSWORD_ERROR_MSG: "Please enter your password!",

    EMAIL_REGEX:  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    EMAIL_ERROR_MSG: "Valid email is required.",
    TAKEN_EMAIL_ERROR_MSG: "Email address is taken!.",
    WRONG_EMAIL_ERROR_MSG: "Wrong email or password!",

    PHONE_REGEX: /(\+\d{1,3}\s?)?((\(\d{3}\)\s?)|(\d{3})(\s|-?))(\d{3}(\s|-?))(\d{4})(\s?(([E|e]xt[:|.|]?)|x|X)(\s?\d+))?/,
    PHONE_ERROR_MSG: "The phone number must be up to 10 digits in the following formats: +359812345678 / 0891234567 ",

    ADRESS_REGEX:/^([\w\s\W]+[\w\W]?)\s([\d\-\\\/\w]*)?/,
    ADRESS_ERROR_MSG: "The address must be in one of these formats: Bulgaria Blvd., 1463 Ndk, Sofia or 13 Democracy Street",

    TYPEACCOUNT_REGEX: /(\w+)/,
    TYPEACCOUNT_ERROR_MSG:"Please select an account type",

    FUNDS_REGEX: /^(?!0\d)\d*(\.\d+)?$/,
    FUNDS_ERROR_MSG:"Please enter only positive integers",

    IMAGEURL_REGEX: /(https:\/\/)([^\s(["<,>/]*)(\/)[^\s[",><]*(.png|.jpg)(\?[^\s[",><]*)?/g,
    IMAGEURL_ERROR_MSG: "Please enter one of the following formats: https://... or  http://....",

    DONATION_ERROR_MSG:"Please choose numbers greater than 0!",
    BALANCE_ERROR_MSG:" Please choose numbers greater than 0!",

    MESSAGE_MAX_LENGTH: 200,
    MESSAGE_MIN_LENGTH: 1, 
    MESSAGE_ERROR_MSG: "Message must be between 1 and 200 symbols.",

    AGE_REGEX:/^(?:1[01][0-9]|120|1[7-9]|[2-9][0-9])$/,
    AGE_ERROR_MSG: "You must be 17 years of age or older.",

    NEGATIVE_BALANCE_ERROR_MSG: "You don't have enough funds. Please add funds to your balance!",
};

export const POST_VALIDATIONS = {
    TITLE_MIN_LEGTH: 5,
    TITLE_MAX_LEGTH: 100,
    TITLE_ERROR_MSG: "Title must be between 5 and 100 symbols.",
    SUBTITLE_ERROR_MSG: "Subtitle must be between 5 and 100 symbols.",

    IMAGEURL_REGEX: /(https:\/\/)([^\s(["<,>/]*)(\/)[^\s[",><]*(.png|.jpg)(\?[^\s[",><]*)?/g,
    IMAGEURL_ERROR_MSG: "Please enter one of the following formats: https://... or  http://....",

    DESCRIPTION_MIN_LEGTH: 5,
    DESCRIPTION_MAX_LEGTH: 200,
    DESCRIPTION_ERROR_MSG: "Description must be between 5 and 200 symbols.",

    MISSION_MIN_LEGTH: 5,
    MISSION_MAX_LEGTH: 200,
    MISSION_ERROR_MSG: "Misson must be between 5 and 200 symbols.",

    BENEFIT_MIN_LEGTH: 5,
    BENEFIT_MAX_LEGTH: 100,
    BENEFIT_ERROR_MSG: "Benefit must be between 5 and 100 symbols.",

    FUNDS_REGEX: /^(?!0\d)\d*(\.\d+)?$/,
    FUNDS_ERROR_MSG:"Please enter only positive numbers",

    COUNTRY_MAX_LENGTH: 20,
    COUNTRY_MIN_LENGTH: 2, 
    COUNTRY_ERROR_MSG: "Country must be between 2 and 20 symbols.",

    CITY_MAX_LENGTH: 20,
    CITY_MIN_LENGTH: 2, 
    CITY_ERROR_MSG: "City must be between 2 and 20 symbols.",

    DATE_REGEX:/\b([1-9]|[12][0-9]|3[01])\b/,
    DATE_ERROR_MSG: "The date must be between 1 and 31.",

    MONTH_REGEX:/\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|(Nov|Dec)(?:ember)?)/,
    MONTH_ERROR_MSG: "The month must be in one of the following formats: Jan, January, Dec, December.",

    HOUR_REGEX:/^(([0]?[0-9]|1[0-2]):[0-5][0-9][ ][aApP][mM])|((1[3-9]|2[0-3]):[0-5][0-9])$/,
    HOUR_ERROR_MSG: "The time must be in the following format: 09:25 AM or 09:33 PM.",
    
    POST_CODE_REGEX:(/\d{5}([ \-]\d{4})?/)|| (/\d{4}/),
    POST_CODE_ERROR_MSG: "Please enter a correct postal code for the country you have specified.",
    
};

export const countries = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "East Timor": "TP",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands": "FK",
    "Faroe Islands": "FO",
    "Fiji Islands": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and McDonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "North Macedonia": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "North Korea": "KP",
    "Northern Ireland": "GB",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Reunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Helena": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "The Democratic Republic of Congo": "CD",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "UK",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",

};
